const field = (name, label, type = "text", options = {}) => ({ name, label, type, ...options });
const enumField = (name, label, values, options = {}) => field(name, label, "select", {
  options: values.map((value) => ({ value, label: value })),
  ...options,
});

export const resources = {
  properties: {
    title: "Properties",
    description: "Manage registered properties and their details.",
    idField: "property_id",
    listEndpoint: "/properties",
    createEndpoint: "/properties",
    updateEndpoint: (row) => `/properties/${row.property_id}`,
    deleteEndpoint: (row) => `/properties/${row.property_id}`,
    columns: ["property_id", "property_name", "address_reference", "number_of_apartments", "status"],
    createFields: [
      field("property_name", "Property name", "text", { required: true }),
      field("address_reference", "Address reference", "text", { required: true }),
      field("owner_reference", "Owner reference", "text", { required: true }),
      field("number_of_apartments", "Number of apartments", "number", { required: true, min: 1 }),
      enumField("status", "Status", ["ACTIVE", "active"], { required: true, defaultValue: "ACTIVE" }),
    ],
    updateFields: [
      field("property_name", "Property name"),
      field("address_reference", "Address reference"),
      field("owner_reference", "Owner reference"),
      field("number_of_apartments", "Number of apartments", "number", { min: 1 }),
      enumField("status", "Status", ["ACTIVE", "active"]),
    ],
  },
  apartments: {
    title: "Apartments",
    description: "Track apartment details and availability.",
    idField: "apartment_id",
    listEndpoint: "/apartments",
    relatedLookups: [{
      label: "Current tenant",
      endpoint: (row) => `/apartments/${row.apartment_id}/current-tenant`,
    }],
    createEndpoint: (values) => `/properties/${values.property_id}/apartments`,
    updateEndpoint: (row) => `/apartments/${row.apartment_id}`,
    columns: ["apartment_id", "property_id", "apartment_number", "apartment_type", "monthly_rent", "status"],
    createFields: [
      field("property_id", "Property ID", "number", { required: true, min: 1 }),
      field("apartment_number", "Apartment number", "text", { required: true }),
      field("floor_number", "Floor number", "number", { required: true, min: 0 }),
      field("apartment_type", "Apartment type", "text", { required: true }),
      field("monthly_rent", "Monthly rent", "number", { required: true, min: 0.01, step: "0.01" }),
      enumField("status", "Status", ["AVAILABLE", "OCCUPIED", "UNDER_MAINTENANCE"], { required: true, defaultValue: "AVAILABLE" }),
    ],
    updateFields: [
      field("apartment_number", "Apartment number"),
      field("floor_number", "Floor number", "number", { min: 0 }),
      field("apartment_type", "Apartment type"),
      field("monthly_rent", "Monthly rent", "number", { min: 0.01, step: "0.01" }),
      enumField("status", "Status", ["AVAILABLE", "OCCUPIED", "UNDER_MAINTENANCE", "INACTIVE"]),
    ],
  },
  tenants: {
    title: "Tenants",
    description: "Manage tenant profiles and account status.",
    idField: "tenant_id",
    listEndpoint: "/tenants",
    relatedLookups: [
      {
        label: "Rent obligations",
        endpoint: (row) => `/tenants/${row.tenant_id}/rent`,
      },
      {
        label: "Maintenance tickets",
        endpoint: (row) => `/tenants/${row.tenant_id}/maintenance-tickets`,
      },
    ],
    createEndpoint: "/tenants",
    updateEndpoint: (row) => `/tenants/${row.tenant_id}`,
    columns: ["tenant_id", "full_name", "email", "phone_reference", "status"],
    createFields: [
      field("full_name", "Full name", "text", { required: true, minLength: 2 }),
      field("email", "Email address", "email", { required: true }),
      field("phone_reference", "Phone reference", "text", { required: true }),
      field("identity_reference", "Identity reference", "text"),
      enumField("status", "Status", ["ACTIVE", "active"], { required: true, defaultValue: "ACTIVE" }),
    ],
    updateFields: [
      field("full_name", "Full name", "text", { minLength: 2 }),
      field("email", "Email address", "email"),
      field("phone_reference", "Phone reference"),
      field("identity_reference", "Identity reference"),
      enumField("status", "Status", ["ACTIVE", "active"]),
    ],
    actions: [{
      label: "Deactivate",
      permission: "deactivate",
      endpoint: (row) => `/tenants/${row.tenant_id}/deactivate`,
      method: "patch",
      when: (row) => row.status?.toUpperCase() !== "INACTIVE",
      confirm: "Deactivate this tenant?",
    }],
  },
  agreements: {
    title: "Rental agreements",
    description: "Review agreements between tenants and apartments.",
    idField: "agreement_id",
    listEndpoint: "/rental-agreements",
    createEndpoint: "/rental-agreements",
    columns: ["agreement_id", "tenant_id", "apartment_id", "start_date", "end_date", "monthly_rent", "status"],
    createFields: [
      field("tenant_id", "Tenant ID", "number", { required: true, min: 1 }),
      field("apartment_id", "Apartment ID", "number", { required: true, min: 1 }),
      field("start_date", "Start date", "date", { required: true }),
      field("end_date", "End date", "date", { required: true }),
      field("monthly_rent", "Monthly rent", "number", { required: true, min: 0.01, step: "0.01" }),
      field("security_deposit", "Security deposit", "number", { required: true, min: 0, step: "0.01" }),
      enumField("status", "Status", ["ACTIVE", "TERMINATED"], { required: true, defaultValue: "ACTIVE" }),
    ],
    actions: [{
      label: "Terminate",
      permission: "terminate",
      endpoint: (row) => `/rental-agreements/${row.agreement_id}/terminate`,
      method: "patch",
      when: (row) => row.status === "ACTIVE",
      confirm: "Terminate this rental agreement?",
    }],
  },
  "rent-obligations": {
    title: "Rent obligations",
    description: "Review rent due dates, balances, and payment status.",
    idField: "rent_id",
    listEndpoint: "/rent-obligations",
    createEndpoint: "/rent-obligations/generate",
    updateEndpoint: (row) => `/rent-obligations/${row.rent_id}`,
    columns: ["rent_id", "agreement_id", "billing_month", "due_date", "amount_due", "amount_paid", "status"],
    createFields: [
      field("agreement_id", "Agreement ID", "number", { required: true, min: 1 }),
      field("billing_month", "Billing month", "month", { required: true }),
      field("due_date", "Due date", "date", { required: true }),
      field("amount_due", "Amount due", "number", { required: true, min: 0.01, step: "0.01" }),
      field("amount_paid", "Amount paid", "number", { min: 0, step: "0.01", defaultValue: 0 }),
      enumField("status", "Status", ["PENDING", "PARTIALLY_PAID", "PAID", "OVERDUE", "WAIVED"], { required: true, defaultValue: "PENDING" }),
    ],
    updateFields: [
      field("due_date", "Due date", "date"),
      field("amount_paid", "Amount paid", "number", { min: 0, step: "0.01" }),
      enumField("status", "Status", ["PENDING", "PARTIALLY_PAID", "PAID", "OVERDUE", "WAIVED"]),
    ],
  },
  payments: {
    title: "Payments",
    description: "Record payments or retrieve a payment by its API identifier.",
    idField: "payment_id",
    lookupEndpoint: (id) => `/payments/${encodeURIComponent(id)}`,
    createEndpoint: "/payments",
    columns: ["payment_id", "rent_id", "amount", "payment_date", "payment_method", "status"],
    createFields: [
      field("rent_id", "Rent obligation ID", "number", { required: true, min: 1 }),
      field("amount", "Amount", "number", { required: true, min: 0.01, step: "0.01" }),
      field("payment_date", "Payment date", "date", { required: true }),
      enumField("payment_method", "Payment method", ["CASH", "Razorpay", "UPI"], { required: true }),
      field("reference_number", "Reference number", "text", { required: true }),
      enumField("status", "Status", ["PENDING", "SUCCESS"], { required: true, defaultValue: "PENDING" }),
    ],
    razorpayFields: [
      field("rent_id", "Rent obligation ID", "number", { required: true, min: 1 }),
      field("amount", "Amount", "number", { required: true, min: 0.01, step: "0.01" }),
    ],
  },
  technicians: {
    title: "Technicians",
    description: "Manage technician profiles and availability.",
    idField: "technician_id",
    listEndpoint: "/technicians",
    createEndpoint: "/technicians",
    updateEndpoint: (row) => `/technicians/${row.technician_id}/availability`,
    columns: ["technician_id", "name", "specialization", "availability_status", "contact_reference"],
    createFields: [
      field("name", "Full name", "text", { required: true, minLength: 2, maxLength: 100 }),
      field("specialization", "Specialization", "text", { required: true }),
      enumField("availability_status", "Availability", ["AVAILABLE", "BUSY"], { required: true, defaultValue: "AVAILABLE" }),
      field("contact_reference", "Contact reference", "text", { required: true }),
    ],
    updateFields: [
      field("name", "Full name", "text", { minLength: 2, maxLength: 100 }),
      field("specialization", "Specialization"),
      enumField("availability_status", "Availability", ["AVAILABLE", "BUSY"]),
      field("contact_reference", "Contact reference"),
    ],
  },
  roles: {
    title: "Roles",
    description: "View and manage role records exposed by the API.",
    idField: "role_id",
    listEndpoint: "/roles",
    createEndpoint: "/roles",
    updateEndpoint: (row) => `/roles/${row.role_id}`,
    columns: ["role_id", "role_name", "description"],
    createFields: [
      field("role_name", "Role name", "text", { required: true, minLength: 2, maxLength: 50 }),
      field("description", "Description"),
    ],
    updateFields: [
      field("role_name", "Role name", "text", { minLength: 3, maxLength: 100 }),
      field("description", "Description"),
    ],
  },
  "sla-policies": {
    title: "SLA policies",
    description: "Set response and resolution targets for each priority.",
    idField: "sla_id",
    listEndpoint: "/sla-policies",
    createEndpoint: "/sla-policies",
    updateEndpoint: (row) => `/sla-policies/${row.sla_id}`,
    columns: ["sla_id", "priority", "response_target", "resolution_target"],
    createFields: [
      field("priority", "Priority", "text", { required: true }),
      field("response_target", "Response target (minutes)", "number", { required: true, min: 1 }),
      field("resolution_target", "Resolution target (minutes)", "number", { required: true, min: 1 }),
    ],
    updateFields: [
      field("response_target", "Response target (minutes)", "number", { min: 1 }),
      field("resolution_target", "Resolution target (minutes)", "number", { min: 1 }),
    ],
  },
  audit: {
    title: "Audit log",
    description: "Review event data returned by the audit endpoint.",
    idField: "entity_id",
    listEndpoint: "/audit",
    columns: ["event_type", "entity_type", "entity_id", "actor_reference", "metadata_json"],
  },
  "overdue-rent": {
    title: "Overdue rent",
    description: "Rent obligations returned by the overdue-rent report.",
    idField: "rent_id",
    listEndpoint: "/reports/overdue-rent",
    columns: ["rent_id", "agreement_id", "billing_month", "due_date", "amount_due", "amount_paid", "status"],
  },
};
